### ISSUE TITLE
Add documentation for JKU formatted CSV

### ISSUE THREAD

**Issue by sebastian-adam** [urinieto/MotivesExtractor#3]
Hi urinieto,

I was so stoked to find your implementation of the research laid out in the "Identifying Polyphonic Patterns From Audio Recordings" paper. I'm struggling though to figure out how to create the accompanying JKU formatted CSV for the analysis. I'm unable to find elsewhere what that acronym stands for or if there is a common package I can add to my toolkit to get the job done. 

Thanks!
Sebastian

**Comment by urinieto** [comment]
Hi Sebastian,

I'm glad you find this useful! You can find the format specification here:
https://www.music-ir.org/mirex/wiki/2019:Discovery_of_Repeated_Themes_%26_Sections#Submission_Format

(JKU stands for Johannes Kepler University)

Please, let me know if this clarifies the formatting of the data.

Best,
oriol

**Comment by sebastian-adam** [comment]
Hi Oriol,

Yes, this is perfect. Further down the rabbit hole I go. I will not close this issue as I'm not sure your preference, but count it as such for me.

The wiki led me to this catalogue of work which looks interesting as well http://www.tomcollinsresearch.net/research/index.html

Thanks again

**Comment by urinieto** [comment]
Cool, glad this helped. Also, thanks for sharing this link, Tom Collins' work is pretty awesome indeed! Will close this for now.
